"""Bundled entry point - do not edit by hand, regenerated by forge_core.

Runs the generic mis-mcp-runtime server against this plugin's config/data,
using only the vendored source tree next to this file plus whatever
dependencies were installed from requirements.txt.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))

from mis_mcp_runtime.server import main  # noqa: E402

if __name__ == "__main__":
    main()
